[workspace]
changelog_update = false
dependencies_update = false
git_release_enable = false
git_tag_enable = true
pr_branch_prefix = "release/"
publish = true
semver_check = true

[[package]]
name = "synapto"
version_group = "synapto-core"

[[package]]
name = "synapto-derive"
version_group = "synapto-core"

[[package]]
name = "synapto-interface"
version_group = "synapto-core"

[[package]]
name = "synapto-llm"
version_group = "synapto-core"

[[package]]
name = "synapto-shutdown"
version_group = "synapto-core"

[[package]]
name = "synapto-telemetry"
version_group = "synapto-core"

[[package]]
name = "synapto-test"
version_group = "synapto-core"
