[package]
name = "synapto-plugin-behavioral-memory"
description = "Behavioral memory plugin for the Synapto framework"
version = "0.1.0-dev.4"
edition = "2024"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
assistant = [] # FIXME

[dependencies]
synapto-interface.workspace = true
synapto-llm.workspace = true
async-trait.workspace = true
serde.workspace = true
schemars.workspace = true
tokio.workspace = true
tracing.workspace = true
derive_more.workspace = true

[dev-dependencies]
synapto-test.workspace = true
synapto.workspace = true
