[package]
name = "synapto-credentials-typesafe"
description = "TypeSafe API key credentials provider for Synapto"
version = "0.1.0-dev.2"
edition = "2024"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
synapto-interface.workspace = true
async-trait.workspace = true
serde.workspace = true


